
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200" # Mapea el puerto del contenedor al host
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Mapea el puerto del contenedor al host
    environment:
      - NODE_ENV=development
      - DB_URL=${DB_URL} # Usa la URL de la base de datos desde el archivo .env
      - URL_FRONT=${URL_FRONT}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge